development:
  bucket_name: instrocktorbuk
  access_key_id: <AKIAIO5KT6PK4MCU7HSA>
  secret_access_key: <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>

test:
  bucket_name: instrocktorbuk
  access_key_id: <AKIAIO5KT6PK4MCU7HSA>
  secret_access_key: <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>

production:
  bucket_name: instrocktorbuk
  access_key_id: <AKIAIO5KT6PK4MCU7HSA>
  secret_access_key: <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>

